title = "VluxySF"
gitRepoUrl = "https://github.com/greenviper126/VluxySF"
gitSourceBranch = "master"
changelog = true

[docusaurus]
organizationName = "vlux"
projectName = "VluxySF"
deploymentBranch = "gh-pages"
tagline = "The extensible command console for Roblox developers"
titleDelimiter = "•"

url = "https://greenviper126.github.io"
baseUrl = "/VluxySF/"

# TODO: Remove when releasing new website
noIndex = true

[home]
enabled = true
includeReadme = false
