[package]
name = "greenviper126/vluxysf"
description = "Sound fetching system with a focus on simplicity and saving memory!"
version = "0.3.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = ["VluxySF", "default.project.json", "LICENSE"]

exclude = [
    "assets",
    "docs",
    "build",
    "PackageTests",
    "Tests",
    "moonwave.toml",
    "stylua.toml",
    "sourcemap.json",
]

[server-dependencies]

#main:

#optional:

[dev-dependencies]

#main:

#optional:


[dependencies]

#main:

#optional:
